[package]
name = "md5"
version = "0.2.0"
authors = ["bitdoer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rand = "0.7.3"
criterion = "0.3.3"

[[bench]]
name = "benches"
harness = false